version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
       - 8080:8080
       - 5005:5005
 #   environment:
 #     - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005
    